spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 6713596081-cpc2785dnmemelg0tq2t0dfhagcthksc.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            #authorization-grant-type: authorization_code
            #client-authentication-method: post
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-name-attribute: sub
