import type { Metadata } from "next";
import "../styles/globals.scss";
import { Navbar, Footer } from "@components";

export const metadata: Metadata = {
  title: "Pet Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
