import type { Metadata } from "next";
import "../styles/globals.scss";
import StoreProvider from "./StoreProvider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Pet Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body>
          {children}
          <Toaster richColors />
        </body>
      </StoreProvider>
    </html>
  );
}
